config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get    "/",               to: "tasks#index"

  get    "tasks",          to: "tasks#index"

  get    "tasks/new",      to: "tasks#new", as: :task_new
  get    "tasks/:id",      to: "tasks#show", as: :task
  post   "tasks",          to: "tasks#create"

  # NB: The `show` route needs to be *after* `new` route.

  patch  "tasks/:id",      to: "tasks#update"

  delete "tasks/:id",      to: "tasks#destroy"
  get    "tasks/:id/edit", to: "tasks#edit", as: :task_edit
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def create
    Task.create!(task_params)
    redirect_to tasks_path
  end

  def new
    @task = Task.new
  end

  def show
    @task = Task.find(params[:id])
  end

  def edit
    # @restaurant = Restaurant.find(params[:id])
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>

<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <%= f.label :completed %>
  <%= f.text_field :completed %>

  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1>Liste de toutes mes tâches</h1>

<ul>
  <% @tasks.each do |task| %>
    <li>
      <%= task.completed ? "[X] - " : "[ ] - " %>
      <%= fa_icon "edit"%>
      <%= link_to task.title, task_path(task) %>

      <%= link_to task_path(task), method: :delete do %>
        <%= fa_icon "trash" %>
      <% end %>
    </li>
  <% end %>
</ul>

<h2>
  <%= fa_icon "plus-circle"%>
  <%= link_to "New Task", task_new_path %>
</h2>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<div>
  <h1> Titre: <%= @task.title %></h1>
  <h2> Détails: <%= @task.details %> </h2>
  <h2> Completed? <%= @task.completed %> </h2>
  <%= fa_icon "undo"%>
  <%= link_to "Back to the list", tasks_path %>
  <%= fa_icon "edit"%>
  <%= link_to "Edit the task", task_edit_path %>
  <%= link_to task_path(@task), method: :delete do %>
    <%= fa_icon "trash" %>
  <% end %>
</div>